### ISSUE TITLE
[Feature Request] Add Comment Feature

### ISSUE THREAD

**Issue by MuTong233** [SIyuyuko/yhc-web#2]
Please add a comment section so visitors can comment below your website!
Don't you think this is a very good idea to get people involved?

**Comment by SIyuyuko** [comment]
Well it will be added in future if more and more requests are pulled like this.
I did not add comment feature because most players communicate things of game in qq group chat, and few people will prefer to remark words in website.
If you do have something to say, you can ask me through qq or email. You can find me [here](https://siyuyuko.github.io/yhc-web/about/staff.html).
